name: Pull Request Comment
on:
  issue_comment:
    types:
      [created]
jobs:
  one:
    name: Check for 're-test' trigger
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "re-test"
      - name: Cancelling workflow if trigger is not found
        uses: andymckay/cancel-action@0.2
        if: steps.check.outputs.triggered == 'false'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
      - name: Client Yarn Install
        working-directory: client
        run: |
          yarn install
      - name: Client Unit Tests
        working-directory: client
        run: |
          CI=true yarn test
      - name: Server Yarn Install
        working-directory: server
        run: |
          yarn install
      - name: Server Unit Tests
        working-directory: server
        run: |
          CI=true yarn test
