version: 0.2

phases:
  install:
    commands:
      # all this is already installed in CodeBuild
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd server
      - yarn
  build:
    commands:
      - echo Testing...
      - CI=true yarn test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package.json
    - src/**/*
    - node_modules/**/*
  base-directory: 'server
