# don't need loadbalancer for now
AWSTemplateFormatVersion: "2010-09-09"
Description: platf0rm-2 load balancer
# Parameters:
# this tag would identify named resources. i.e. staging:VPC, instead of VPC
# EnvironmentName:
#   Default:
#   Description: whether it's staging
#   Type: String
Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: training-aws-lb
      Subnets: "platf0rm-2 public"
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for loadbalancer to services on ECS
      # VpcId:
      #   Fn::ImportValue: "VPC"
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup
  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: aws-platf0rm2-default
      # VpcId:
      #   Fn::ImportValue: "VPC"
      Protocol: HTTP
      Port: 80
Outputs:
  LoadBalancerDNS:
    Description: Domain name for the loadbalancer
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: Platf0rm2DomainName
  LoadBalancerListener:
    Description: loadbalancer listener
    Value: !Ref LoadBalancerListener
    Export:
      Name: Platf0rm2LoadBalancerListener
  LoadBalancerSecurityGroup:
    Description: Loadbalancer security group
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: Platf0rm2LoadBalancerSecurityGroup
