name: PR Lint and Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Client Linting
      #   working-directory: client
      #   run: |
      #     yarn eslint
      # - name: Server Linting
      #   working-directory: server
      #   run: |
      #     yarn eslint
      - name: Client Yarn Install
        working-directory: client
        run: |
          yarn install
      - name: Client Unit Tests
        working-directory: client
        run: |
          CI=true yarn test
      - name: Server Yarn Install
        working-directory: server
        run: |
          yarn install
      - name: Server Unit Tests
        working-directory: server
        run: |
          ./node_modules/ts-node/dist/bin.js -r tsconfig-paths/register ./test
